
server:
  port: 8080
  servlet:
    context-path: /
  
logging:
  level:
    web: debug
    org:
      hibernate:
        SQL: debug

aplicacion:
  nombre: Tutorial Spring Boot - Ayuntamiento de Zaragoza
